# Generated by Django 5.2.17 on 2026-09-15 10:50

import django.core.serializers.json
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('sales', '0020_recurringinvoicetemplateline_cess_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider_key', models.CharField(default='manual', max_length=32)),
                ('irn', models.CharField(blank=True, max_length=64)),
                ('ack_no', models.CharField(blank=True, max_length=32)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('signed_invoice', models.TextField(blank=True)),
                ('signed_qr_code', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error_message', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='einvoices', to='sales.creditnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='einvoices', to='sales.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='compliance__organiz_a67edb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit_note__isnull', True), ('invoice__isnull', False)), models.Q(('credit_note__isnull', False), ('invoice__isnull', True)), _connector='OR'), name='einvoice_targets_exactly_one_document'), models.UniqueConstraint(condition=models.Q(('irn', ''), _negated=True), fields=('organization', 'irn'), name='uniq_einvoice_irn_per_org'), models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('organization', 'invoice'), name='uniq_live_einvoice_per_invoice'), models.UniqueConstraint(condition=models.Q(('credit_note__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('organization', 'credit_note'), name='uniq_live_einvoice_per_credit_note')],
            },
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider_key', models.CharField(default='manual', max_length=32)),
                ('ewb_no', models.CharField(blank=True, max_length=16)),
                ('ewb_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('transport_mode', models.CharField(choices=[('1', 'Road'), ('2', 'Rail'), ('3', 'Air'), ('4', 'Ship')], default='1', max_length=2)),
                ('transporter_gstin', models.CharField(blank=True, max_length=15)),
                ('transporter_name', models.CharField(blank=True, max_length=128)),
                ('transport_doc_no', models.CharField(blank=True, max_length=32)),
                ('vehicle_number', models.CharField(blank=True, max_length=16)),
                ('vehicle_type', models.CharField(choices=[('R', 'Regular'), ('O', 'Over-dimensional cargo')], default='R', max_length=2)),
                ('consignment_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error_message', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('delivery_challan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ewaybills', to='sales.deliverychallan')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ewaybills', to='sales.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='compliance__organiz_03568a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delivery_challan__isnull', True), ('invoice__isnull', False)), models.Q(('delivery_challan__isnull', False), ('invoice__isnull', True)), _connector='OR'), name='ewaybill_targets_exactly_one_document'), models.UniqueConstraint(condition=models.Q(('ewb_no', ''), _negated=True), fields=('organization', 'ewb_no'), name='uniq_ewaybill_number_per_org'), models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('organization', 'invoice'), name='uniq_live_ewaybill_per_invoice'), models.UniqueConstraint(condition=models.Q(('delivery_challan__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('organization', 'delivery_challan'), name='uniq_live_ewaybill_per_challan'), models.CheckConstraint(condition=models.Q(('distance_km__lte', 4000)), name='ewaybill_distance_within_api_limit')],
            },
        ),
    ]
