# Generated by Django 5.2.17 on 2026-09-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_expense_project'),
        ('tax', '0003_seed_state_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='place_of_supply_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_treatment',
            field=models.CharField(choices=[('registered', 'Registered business'), ('unregistered', 'Unregistered business'), ('consumer', 'Consumer (B2C)'), ('overseas', 'Overseas'), ('sez', 'SEZ unit or developer'), ('deemed_export', 'Deemed export')], default='unregistered', max_length=20),
        ),
    ]
