# Generated by Django 5.2.17 on 2026-09-15 10:19

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
        ('items', '0003_item_tax_rate'),
        ('projects', '0002_enable_rls'),
        ('purchases', '0004_vendor_place_of_supply_state_vendor_tax_treatment'),
        ('sales', '0018_customer_place_of_supply_state_and_more'),
        ('tax', '0003_seed_state_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bill',
            name='cgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bill',
            name='igst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='place_of_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bill',
            name='supply_nature',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('intra_state', 'Intra-State (CGST + SGST/UTGST)'), ('inter_state', 'Inter-State (IGST)'), ('export_with_tax', 'Export with payment of tax (IGST)'), ('export_without_tax', 'Export under LUT/bond (zero-rated)'), ('sez_with_tax', 'SEZ supply with payment of tax (IGST)'), ('sez_without_tax', 'SEZ supply under LUT/bond (zero-rated)'), ('deemed_export', 'Deemed export')], default='unspecified', max_length=24),
        ),
        migrations.AddField(
            model_name='bill',
            name='supply_type',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('B2B', 'Business to business'), ('SEZWP', 'SEZ with payment of tax'), ('SEZWOP', 'SEZ without payment of tax'), ('EXPWP', 'Export with payment of tax'), ('EXPWOP', 'Export without payment of tax'), ('DEXP', 'Deemed export')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='bill',
            name='withholding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bill',
            name='withholding_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.withholdingsection'),
        ),
        migrations.AddField(
            model_name='billline',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billline',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='billline',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billline',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billline',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='place_of_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='expense',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='supply_nature',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('intra_state', 'Intra-State (CGST + SGST/UTGST)'), ('inter_state', 'Inter-State (IGST)'), ('export_with_tax', 'Export with payment of tax (IGST)'), ('export_without_tax', 'Export under LUT/bond (zero-rated)'), ('sez_with_tax', 'SEZ supply with payment of tax (IGST)'), ('sez_without_tax', 'SEZ supply under LUT/bond (zero-rated)'), ('deemed_export', 'Deemed export')], default='unspecified', max_length=24),
        ),
        migrations.AddField(
            model_name='expense',
            name='supply_type',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('B2B', 'Business to business'), ('SEZWP', 'SEZ with payment of tax'), ('SEZWOP', 'SEZ without payment of tax'), ('EXPWP', 'Export with payment of tax'), ('EXPWOP', 'Export without payment of tax'), ('DEXP', 'Deemed export')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='place_of_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supply_nature',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('intra_state', 'Intra-State (CGST + SGST/UTGST)'), ('inter_state', 'Inter-State (IGST)'), ('export_with_tax', 'Export with payment of tax (IGST)'), ('export_without_tax', 'Export under LUT/bond (zero-rated)'), ('sez_with_tax', 'SEZ supply with payment of tax (IGST)'), ('sez_without_tax', 'SEZ supply under LUT/bond (zero-rated)'), ('deemed_export', 'Deemed export')], default='unspecified', max_length=24),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supply_type',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('B2B', 'Business to business'), ('SEZWP', 'SEZ with payment of tax'), ('SEZWOP', 'SEZ without payment of tax'), ('EXPWP', 'Export with payment of tax'), ('EXPWOP', 'Export without payment of tax'), ('DEXP', 'Deemed export')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='recurringbilltemplate',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringbilltemplate',
            name='place_of_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='recurringbilltemplate',
            name='supply_nature',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('intra_state', 'Intra-State (CGST + SGST/UTGST)'), ('inter_state', 'Inter-State (IGST)'), ('export_with_tax', 'Export with payment of tax (IGST)'), ('export_without_tax', 'Export under LUT/bond (zero-rated)'), ('sez_with_tax', 'SEZ supply with payment of tax (IGST)'), ('sez_without_tax', 'SEZ supply under LUT/bond (zero-rated)'), ('deemed_export', 'Deemed export')], default='unspecified', max_length=24),
        ),
        migrations.AddField(
            model_name='recurringbilltemplate',
            name='supply_type',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('B2B', 'Business to business'), ('SEZWP', 'SEZ with payment of tax'), ('SEZWOP', 'SEZ without payment of tax'), ('EXPWP', 'Export with payment of tax'), ('EXPWOP', 'Export without payment of tax'), ('DEXP', 'Deemed export')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='recurringexpensetemplate',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringexpensetemplate',
            name='place_of_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='recurringexpensetemplate',
            name='supply_nature',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('intra_state', 'Intra-State (CGST + SGST/UTGST)'), ('inter_state', 'Inter-State (IGST)'), ('export_with_tax', 'Export with payment of tax (IGST)'), ('export_without_tax', 'Export under LUT/bond (zero-rated)'), ('sez_with_tax', 'SEZ supply with payment of tax (IGST)'), ('sez_without_tax', 'SEZ supply under LUT/bond (zero-rated)'), ('deemed_export', 'Deemed export')], default='unspecified', max_length=24),
        ),
        migrations.AddField(
            model_name='recurringexpensetemplate',
            name='supply_type',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('B2B', 'Business to business'), ('SEZWP', 'SEZ with payment of tax'), ('SEZWOP', 'SEZ without payment of tax'), ('EXPWP', 'Export with payment of tax'), ('EXPWOP', 'Export without payment of tax'), ('DEXP', 'Deemed export')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='cgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='igst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='place_of_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode'),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='sgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='supply_nature',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('intra_state', 'Intra-State (CGST + SGST/UTGST)'), ('inter_state', 'Inter-State (IGST)'), ('export_with_tax', 'Export with payment of tax (IGST)'), ('export_without_tax', 'Export under LUT/bond (zero-rated)'), ('sez_with_tax', 'SEZ supply with payment of tax (IGST)'), ('sez_without_tax', 'SEZ supply under LUT/bond (zero-rated)'), ('deemed_export', 'Deemed export')], default='unspecified', max_length=24),
        ),
        migrations.AddField(
            model_name='vendorcredit',
            name='supply_type',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('B2B', 'Business to business'), ('SEZWP', 'SEZ with payment of tax'), ('SEZWOP', 'SEZ without payment of tax'), ('EXPWP', 'Export with payment of tax'), ('EXPWOP', 'Export without payment of tax'), ('DEXP', 'Deemed export')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cess_amount', 0), ('cgst_amount', 0), ('igst_amount', 0), ('sgst_amount', 0)), ('tax_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cgst_amount'), '+', models.F('sgst_amount')), '+', models.F('igst_amount')), '+', models.F('cess_amount'))), _connector='OR'), name='bill_line_tax_components_sum_to_tax_amount'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cess_amount', 0), ('cgst_amount', 0), ('igst_amount', 0), ('sgst_amount', 0)), ('tax_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cgst_amount'), '+', models.F('sgst_amount')), '+', models.F('igst_amount')), '+', models.F('cess_amount'))), _connector='OR'), name='expense_tax_components_sum_to_tax_amount'),
        ),
        migrations.AddConstraint(
            model_name='vendorcreditline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cess_amount', 0), ('cgst_amount', 0), ('igst_amount', 0), ('sgst_amount', 0)), ('tax_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cgst_amount'), '+', models.F('sgst_amount')), '+', models.F('igst_amount')), '+', models.F('cess_amount'))), _connector='OR'), name='vendor_credit_line_tax_components_sum_to_tax_amount'),
        ),
    ]
