# Generated by Django 5.2.17 on 2026-09-15 10:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_union_territory', models.BooleanField(default=False)),
                ('uses_utgst', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GST state code',
                'verbose_name_plural': 'GST state codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxAccountMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('cgst', 'Central GST'), ('sgst_utgst', 'State / Union Territory GST'), ('igst', 'Integrated GST'), ('cess', 'Compensation cess'), ('tds', 'Tax deducted at source'), ('tcs', 'Tax collected at source')], max_length=16)),
                ('direction', models.CharField(choices=[('output', 'Output tax (liability)'), ('input', 'Input tax (asset)'), ('rcm_payable', 'Reverse-charge liability')], max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['direction', 'component'],
                'indexes': [models.Index(fields=['organization', 'direction'], name='tax_taxacco_organiz_f23c30_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'component', 'direction'), name='uniq_tax_account_mapping_per_org')],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition scheme'), ('unregistered', 'Unregistered'), ('sez_unit', 'SEZ unit'), ('sez_developer', 'SEZ developer'), ('isd', 'Input service distributor'), ('non_resident', 'Non-resident taxable person'), ('uin', 'UIN holder')], default='regular', max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('composition_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Only meaningful when registration_type is COMPOSITION.', max_digits=5)),
                ('einvoice_enabled', models.BooleanField(default=False)),
                ('einvoice_reporting_window_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ewaybill_threshold', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Consignment value at or above which an e-way bill is required.', max_digits=18)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.statecode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization',), name='uniq_tax_profile_per_org'), models.CheckConstraint(condition=models.Q(('composition_rate__gte', Decimal('0'))), name='tax_profile_composition_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('ewaybill_threshold__gte', Decimal('0'))), name='tax_profile_ewaybill_threshold_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['rate', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='tax_taxrate_organiz_fa4319_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='uniq_tax_rate_name_per_org'), models.CheckConstraint(condition=models.Q(('rate__gte', Decimal('0'))), name='tax_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('cess_rate__gte', Decimal('0'))), name='tax_rate_cess_nonnegative'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tax_rate_effective_window_ordered')],
            },
        ),
        migrations.CreateModel(
            name='WithholdingSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(choices=[('tds', 'Tax deducted at source'), ('tcs', 'Tax collected at source')], max_length=8)),
                ('applies_to', models.CharField(choices=[('purchase', 'Purchases (we deduct)'), ('sales', 'Sales (we collect)')], max_length=16)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Reference only - this phase does not track cumulative payee turnover.', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='tax_withhol_organiz_7cd0fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uniq_withholding_section_per_org'), models.CheckConstraint(condition=models.Q(('rate__gte', Decimal('0')), ('rate__lte', Decimal('100'))), name='withholding_rate_between_0_and_100'), models.CheckConstraint(condition=models.Q(('threshold_amount__gte', Decimal('0'))), name='withholding_threshold_nonnegative')],
            },
        ),
    ]
