from django.urls import path

from reports.api.views import (
    APAgeingView,
    ARAgeingView,
    BalanceSheetView,
    CashFlowView,
    CustomerBalancesView,
    ExpensesByCategoryView,
    GeneralLedgerReportView,
    GSTR1SummaryView,
    GSTR3BSummaryView,
    GSTSummaryView,
    InputTaxRegisterView,
    InventoryMovementView,
    InventoryValuationView,
    JournalReportView,
    LowStockReportView,
    OutputTaxRegisterView,
    OutstandingBillsView,
    OutstandingInvoicesView,
    OverdueBillsView,
    OverdueInvoicesView,
    ProfitAndLossView,
    ProjectProfitabilityReportView,
    PurchasesByItemView,
    PurchasesByVendorView,
    SalesByCustomerView,
    SalesByItemView,
    StockAdjustmentReportView,
    StockSummaryView,
    TrialBalanceView,
    VendorBalancesView,
)

urlpatterns = [
    path("reports/profit-loss/", ProfitAndLossView.as_view(), name="reports-profit-loss"),
    path("reports/balance-sheet/", BalanceSheetView.as_view(), name="reports-balance-sheet"),
    path("reports/cash-flow/", CashFlowView.as_view(), name="reports-cash-flow"),
    path("reports/trial-balance/", TrialBalanceView.as_view(), name="reports-trial-balance"),
    path("reports/general-ledger/", GeneralLedgerReportView.as_view(), name="reports-general-ledger"),
    path("reports/journals/", JournalReportView.as_view(), name="reports-journals"),
    path("reports/receivables/ageing/", ARAgeingView.as_view(), name="reports-ar-ageing"),
    path("reports/receivables/customer-balances/", CustomerBalancesView.as_view(), name="reports-customer-balances"),
    path("reports/receivables/outstanding-invoices/", OutstandingInvoicesView.as_view(), name="reports-outstanding-invoices"),
    path("reports/receivables/overdue-invoices/", OverdueInvoicesView.as_view(), name="reports-overdue-invoices"),
    path("reports/sales/by-customer/", SalesByCustomerView.as_view(), name="reports-sales-by-customer"),
    path("reports/sales/by-item/", SalesByItemView.as_view(), name="reports-sales-by-item"),
    path("reports/payables/ageing/", APAgeingView.as_view(), name="reports-ap-ageing"),
    path("reports/payables/vendor-balances/", VendorBalancesView.as_view(), name="reports-vendor-balances"),
    path("reports/payables/outstanding-bills/", OutstandingBillsView.as_view(), name="reports-outstanding-bills"),
    path("reports/payables/overdue-bills/", OverdueBillsView.as_view(), name="reports-overdue-bills"),
    path("reports/purchases/by-vendor/", PurchasesByVendorView.as_view(), name="reports-purchases-by-vendor"),
    path("reports/purchases/by-item/", PurchasesByItemView.as_view(), name="reports-purchases-by-item"),
    path("reports/expenses/by-category/", ExpensesByCategoryView.as_view(), name="reports-expenses-by-category"),
    path("reports/inventory/summary/", StockSummaryView.as_view(), name="reports-inventory-summary"),
    path("reports/inventory/valuation/", InventoryValuationView.as_view(), name="reports-inventory-valuation"),
    path("reports/inventory/movements/", InventoryMovementView.as_view(), name="reports-inventory-movements"),
    path("reports/inventory/adjustments/", StockAdjustmentReportView.as_view(), name="reports-inventory-adjustments"),
    path("reports/inventory/low-stock/", LowStockReportView.as_view(), name="reports-inventory-low-stock"),
    path("reports/tax/output-register/", OutputTaxRegisterView.as_view(), name="reports-tax-output-register"),
    path("reports/tax/input-register/", InputTaxRegisterView.as_view(), name="reports-tax-input-register"),
    path("reports/tax/gstr1-summary/", GSTR1SummaryView.as_view(), name="reports-tax-gstr1-summary"),
    path("reports/tax/gstr3b-summary/", GSTR3BSummaryView.as_view(), name="reports-tax-gstr3b-summary"),
    path("reports/tax/gst-summary/", GSTSummaryView.as_view(), name="reports-tax-gst-summary"),
    path("reports/projects/profitability/", ProjectProfitabilityReportView.as_view(), name="reports-project-profitability"),
]
