# Generated by Django 5.2.17 on 2026-09-15 07:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('items', '0002_enable_rls'),
        ('sales', '0017_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('billing_method', models.CharField(choices=[('non_billable', 'Non-billable'), ('hourly', 'Hourly rate'), ('fixed_fee', 'Fixed fee')], default='hourly', max_length=16)),
                ('default_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fixed_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('budget_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billable_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced')], default='draft', max_length=16)),
                ('is_billable', models.BooleanField(default=False)),
                ('billable_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='sales.invoiceline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='projects_pr_organiz_8941e0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'customer'], name='projects_pr_organiz_46da28_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'project_code'), name='uniq_project_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('default_hourly_rate__isnull', True), ('default_hourly_rate__gte', Decimal('0')), _connector='OR'), name='project_default_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='project_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['organization', 'project'], name='projects_pr_organiz_d1abb6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['organization', 'user'], name='projects_pr_organiz_489acb_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.CheckConstraint(condition=models.Q(('billable_rate__isnull', True), ('billable_rate__gte', Decimal('0')), _connector='OR'), name='project_member_billable_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.CheckConstraint(condition=models.Q(('cost_rate__isnull', True), ('cost_rate__gte', Decimal('0')), _connector='OR'), name='project_member_cost_rate_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'project', 'is_active'], name='projects_ta_organiz_295bb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_task_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__isnull', True), ('hourly_rate__gte', Decimal('0')), _connector='OR'), name='task_hourly_rate_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['organization', 'project', 'status'], name='projects_ti_organiz_e32379_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['organization', 'user', 'entry_date'], name='projects_ti_organiz_f9374a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['organization', 'status', 'is_billable'], name='projects_ti_organiz_f2c966_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task'], name='projects_ti_task_id_126387_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='time_entry_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__lte', Decimal('24'))), name='time_entry_hours_max_24'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('billable_rate__isnull', True), ('billable_rate__gte', Decimal('0')), _connector='OR'), name='time_entry_billable_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('cost_rate__isnull', True), ('cost_rate__gte', Decimal('0')), _connector='OR'), name='time_entry_cost_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice_line__isnull', False), ('status', 'invoiced')), models.Q(models.Q(('status', 'invoiced'), _negated=True), ('invoice_line__isnull', True)), _connector='OR'), name='time_entry_invoiced_iff_linked'),
        ),
    ]
