# Generated by Django 5.2.17 on 2026-09-15 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=16)),
                ('account_subtype', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['organization', 'account_type'], name='accounting__organiz_da5c67_idx'), models.Index(fields=['organization', 'parent'], name='accounting__organiz_c3bcaf_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uniq_account_code_per_org')],
            },
        ),
    ]
