# Generated by Django 5.2.17 on 2026-09-15 03:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_enable_rls'),
        ('accounts', '0003_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_number', models.CharField(blank=True, max_length=32)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('posting_date', models.DateField()),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=16)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='accounting.journalentry')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-posting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('base_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('base_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['journal_entry', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status', 'posting_date'], name='accounting__organiz_88e558_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'source_type', 'source_id'], name='accounting__organiz_4ba640_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('journal_number', ''), _negated=True), fields=('organization', 'journal_number'), name='uniq_journal_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['organization', 'account'], name='accounting__organiz_f5119c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['journal_entry', 'line_number'], name='accounting__journal_e4a488_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='journal_line_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journal_line_not_both_debit_and_credit'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _negated=True), name='journal_line_not_both_zero'),
        ),
    ]
