# Generated by Django 5.2.17 on 2026-09-15 03:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='HsnSacCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(choices=[('hsn', 'HSN (goods)'), ('sac', 'SAC (services)')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'HSN/SAC code',
                'verbose_name_plural': 'HSN/SAC codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=False)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('tax_category', models.CharField(blank=True, max_length=64)),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('hsn_sac_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.hsnsaccode')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.unitofmeasure')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='hsnsaccode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_hsn_sac_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_unit_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'item_type'], name='items_item_organiz_e11014_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'is_active'], name='items_item_organiz_4d84e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('organization', 'sku'), name='uniq_item_sku_per_org'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('item_type', 'service'), ('track_inventory', True), _negated=True), name='service_item_cannot_track_inventory'),
        ),
    ]
