# Generated by Django 5.2.17 on 2026-09-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_enable_rls'),
        ('tax', '0003_seed_state_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.taxrate'),
        ),
    ]
