# Generated by Django 5.2.17 on 2026-09-16 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('stop_on_failure', models.BooleanField(default=False)),
                ('max_runs_per_period', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=32)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automation.automationrule')),
            ],
            options={
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationActionConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('action_id', models.CharField(max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automationrule')),
            ],
            options={
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization', 'trigger_type', 'status'], name='automation__organiz_f536fe_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization', 'created_at'], name='automation__organiz_850c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationcondition',
            index=models.Index(fields=['rule', 'order'], name='automation__rule_id_e6241e_idx'),
        ),
        migrations.AddIndex(
            model_name='automationactionconfig',
            index=models.Index(fields=['rule', 'order'], name='automation__rule_id_a330d0_idx'),
        ),
    ]
