# Generated by Django 5.2.17 on 2026-09-16 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('automation', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['organization', 'dispatched_at'], name='automation__organiz_40ed59_idx'), models.Index(fields=['organization', 'event_type'], name='automation__organiz_7c44dd_idx')],
            },
        ),
    ]
