# Generated by Django 5.2.17 on 2026-09-16 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('automation', '0004_enable_rls_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_version', models.PositiveIntegerField()),
                ('trigger_source', models.CharField(choices=[('event', 'Event'), ('schedule', 'Schedule'), ('manual', 'Manual')], max_length=16)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('conditions_snapshot', models.JSONField(blank=True, default=list)),
                ('actions_snapshot', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('executed_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automation.automationrule')),
                ('trigger_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automation.automationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='automation.automationexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStepExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('action_id', models.CharField(max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('failure_category', models.CharField(blank=True, choices=[('validation_error', 'Validation error'), ('permission_error', 'Permission error'), ('target_missing', 'Target missing'), ('transient_external_error', 'Transient external error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate limited'), ('domain_conflict', 'Domain conflict'), ('safety_limit', 'Safety limit'), ('unexpected_error', 'Unexpected error')], max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.automationexecution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['execution', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['organization', 'rule', 'status'], name='automation__organiz_144c79_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['organization', 'created_at'], name='automation__organiz_ef7c4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_event__isnull', False)), fields=('rule', 'trigger_event'), name='uniq_automation_execution_per_rule_event'),
        ),
        migrations.AddIndex(
            model_name='automationnotification',
            index=models.Index(fields=['organization', 'recipient', 'is_read'], name='automation__organiz_4e1f09_idx'),
        ),
        migrations.AddIndex(
            model_name='automationstepexecution',
            index=models.Index(fields=['execution', 'order'], name='automation__executi_48da81_idx'),
        ),
    ]
