# Generated by Django 5.2.17 on 2026-09-16 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('automation', '0006_enable_rls_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='cooldown_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutomationScanOccurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=64)),
                ('occurrence_date', models.DateField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='automation.automationexecution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_occurrences', to='automation.automationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'rule', 'entity_id'], name='automation__organiz_008ccb_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'entity_id', 'occurrence_date'), name='uniq_automation_scan_occurrence')],
            },
        ),
        migrations.CreateModel(
            name='AutomationSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('next_run_at', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='automation.automationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'next_run_at'], name='automation__organiz_2bb8d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationScheduleOccurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='automation.automationexecution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_occurrences', to='automation.automationrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'scheduled_for'), name='uniq_automation_schedule_occurrence')],
            },
        ),
    ]
