# Generated by Django 5.2.17 on 2026-09-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_enable_rls_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecution',
            name='recovery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
