from django.urls import path

from sales.api.views import (
    CreditNoteDetailView,
    CreditNoteIssueView,
    CreditNoteListCreateView,
    CreditNoteVoidView,
    CustomerDetailView,
    CustomerListCreateView,
    CustomerPaymentDetailView,
    CustomerPaymentListCreateView,
    DeliveryChallanCancelView,
    DeliveryChallanDeliverView,
    DeliveryChallanDetailView,
    DeliveryChallanDispatchView,
    DeliveryChallanListCreateView,
    InvoiceDetailView,
    InvoiceListCreateView,
    InvoicePostView,
    InvoiceVoidView,
    QuoteAcceptView,
    QuoteCancelView,
    QuoteConvertView,
    QuoteDetailView,
    QuoteListCreateView,
    QuoteRejectView,
    QuoteSendView,
    RecurringInvoiceTemplateActivateView,
    RecurringInvoiceTemplateDeactivateView,
    RecurringInvoiceTemplateDetailView,
    RecurringInvoiceTemplateListCreateView,
    SalesOrderCancelView,
    SalesOrderConfirmView,
    SalesOrderDetailView,
    SalesOrderListCreateView,
)

urlpatterns = [
    path("sales/customers/", CustomerListCreateView.as_view(), name="sales-customer-list-create"),
    path("sales/customers/<uuid:pk>/", CustomerDetailView.as_view(), name="sales-customer-detail"),
    path("sales/quotes/", QuoteListCreateView.as_view(), name="sales-quote-list-create"),
    path("sales/quotes/<uuid:pk>/", QuoteDetailView.as_view(), name="sales-quote-detail"),
    path("sales/quotes/<uuid:pk>/send/", QuoteSendView.as_view(), name="sales-quote-send"),
    path("sales/quotes/<uuid:pk>/accept/", QuoteAcceptView.as_view(), name="sales-quote-accept"),
    path("sales/quotes/<uuid:pk>/reject/", QuoteRejectView.as_view(), name="sales-quote-reject"),
    path("sales/quotes/<uuid:pk>/cancel/", QuoteCancelView.as_view(), name="sales-quote-cancel"),
    path("sales/quotes/<uuid:pk>/convert/", QuoteConvertView.as_view(), name="sales-quote-convert"),
    path("sales/orders/", SalesOrderListCreateView.as_view(), name="sales-order-list-create"),
    path("sales/orders/<uuid:pk>/", SalesOrderDetailView.as_view(), name="sales-order-detail"),
    path("sales/orders/<uuid:pk>/confirm/", SalesOrderConfirmView.as_view(), name="sales-order-confirm"),
    path("sales/orders/<uuid:pk>/cancel/", SalesOrderCancelView.as_view(), name="sales-order-cancel"),
    path("sales/deliveries/", DeliveryChallanListCreateView.as_view(), name="sales-delivery-list-create"),
    path("sales/deliveries/<uuid:pk>/", DeliveryChallanDetailView.as_view(), name="sales-delivery-detail"),
    path("sales/deliveries/<uuid:pk>/dispatch/", DeliveryChallanDispatchView.as_view(), name="sales-delivery-dispatch"),
    path("sales/deliveries/<uuid:pk>/deliver/", DeliveryChallanDeliverView.as_view(), name="sales-delivery-deliver"),
    path("sales/deliveries/<uuid:pk>/cancel/", DeliveryChallanCancelView.as_view(), name="sales-delivery-cancel"),
    path("sales/invoices/", InvoiceListCreateView.as_view(), name="sales-invoice-list-create"),
    path("sales/invoices/<uuid:pk>/", InvoiceDetailView.as_view(), name="sales-invoice-detail"),
    path("sales/invoices/<uuid:pk>/post/", InvoicePostView.as_view(), name="sales-invoice-post"),
    path("sales/invoices/<uuid:pk>/void/", InvoiceVoidView.as_view(), name="sales-invoice-void"),
    path("sales/payments/", CustomerPaymentListCreateView.as_view(), name="sales-payment-list-create"),
    path("sales/payments/<uuid:pk>/", CustomerPaymentDetailView.as_view(), name="sales-payment-detail"),
    path("sales/credit-notes/", CreditNoteListCreateView.as_view(), name="sales-credit-note-list-create"),
    path("sales/credit-notes/<uuid:pk>/", CreditNoteDetailView.as_view(), name="sales-credit-note-detail"),
    path("sales/credit-notes/<uuid:pk>/issue/", CreditNoteIssueView.as_view(), name="sales-credit-note-issue"),
    path("sales/credit-notes/<uuid:pk>/void/", CreditNoteVoidView.as_view(), name="sales-credit-note-void"),
    path(
        "sales/recurring-invoices/", RecurringInvoiceTemplateListCreateView.as_view(),
        name="sales-recurring-invoice-list-create",
    ),
    path(
        "sales/recurring-invoices/<uuid:pk>/", RecurringInvoiceTemplateDetailView.as_view(),
        name="sales-recurring-invoice-detail",
    ),
    path(
        "sales/recurring-invoices/<uuid:pk>/activate/", RecurringInvoiceTemplateActivateView.as_view(),
        name="sales-recurring-invoice-activate",
    ),
    path(
        "sales/recurring-invoices/<uuid:pk>/deactivate/", RecurringInvoiceTemplateDeactivateView.as_view(),
        name="sales-recurring-invoice-deactivate",
    ),
]
