# Generated by Django 5.2.17 on 2026-09-15 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
        ('inventory', '0004_enable_rls'),
        ('items', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_date', models.DateField()),
                ('reason', models.CharField(choices=[('physical_count', 'Physical Count'), ('damaged', 'Damaged'), ('shrinkage', 'Shrinkage'), ('found', 'Found Stock'), ('correction', 'Data Correction'), ('other', 'Other')], max_length=32)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('contra_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stockadjustment')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['adjustment', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'status', 'adjustment_date'], name='inventory_s_organiz_5b6e50_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentline',
            index=models.Index(fields=['adjustment', 'line_number'], name='inventory_s_adjustm_351631_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='adjustment_line_quantity_positive'),
        ),
    ]
