# Generated by Django 5.2.17 on 2026-09-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_enable_rls'),
    ]

    operations = [
        # Backs StockMovement.sequence — a deterministic insertion-order
        # tiebreaker for chronological replay (weighted-average valuation),
        # since the UUID primary key is random and unsafe for that purpose.
        # Plain SQL because Django's AutoField requires primary_key=True.
        migrations.RunSQL(
            sql="CREATE SEQUENCE inventory_stockmovement_seq;",
            reverse_sql="DROP SEQUENCE inventory_stockmovement_seq;",
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['movement_date', 'sequence']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sequence',
            field=models.BigIntegerField(default=0, editable=False, unique=True),
        ),
    ]
