# Generated by Django 5.2.17 on 2026-09-15 04:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('payment_terms_days', models.PositiveIntegerField(default=0)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='sales_custo_organiz_0ee899_idx'), models.Index(fields=['organization', 'display_name'], name='sales_custo_organiz_b14767_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'customer_code'), name='uniq_customer_code_per_org'), models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', Decimal('0')), _connector='OR'), name='customer_credit_limit_nonnegative')],
            },
        ),
    ]
