# Generated by Django 5.2.17 on 2026-09-15 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('inventory', '0007_alter_stockmovement_options_stockmovement_sequence'),
        ('items', '0002_enable_rls'),
        ('sales', '0006_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challan_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('challan_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('source_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='sales.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-challan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverychallan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('source_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='sales.salesorderline')),
            ],
            options={
                'ordering': ['challan', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['organization', 'status', 'challan_date'], name='sales_deliv_organiz_069080_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['organization', 'customer'], name='sales_deliv_organiz_7195fe_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['organization', 'source_sales_order'], name='sales_deliv_organiz_feeb6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallan',
            constraint=models.UniqueConstraint(fields=('organization', 'challan_number'), name='uniq_delivery_challan_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='deliverychallanline',
            index=models.Index(fields=['challan', 'line_number'], name='sales_deliv_challan_a5d660_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallanline',
            index=models.Index(fields=['source_order_line'], name='sales_deliv_source__40f742_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallanline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='delivery_line_quantity_positive'),
        ),
    ]
