# Generated by Django 5.2.17 on 2026-09-15 05:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
        ('inventory', '0007_alter_stockmovement_options_stockmovement_sequence'),
        ('items', '0002_enable_rls'),
        ('sales', '0012_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('void', 'Void')], default='draft', max_length=16)),
                ('reason', models.CharField(choices=[('return', 'Return'), ('pricing_error', 'Pricing Error'), ('discount', 'Discount'), ('goodwill', 'Goodwill'), ('other', 'Other')], default='other', max_length=16)),
                ('credit_note_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.invoice')),
                ('tax_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('unapplied_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-credit_note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('hsn_sac_snapshot', models.CharField(blank=True, max_length=16)),
                ('tax_label', models.CharField(blank=True, max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('line_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('restock', models.BooleanField(default=False)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.creditnote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('source_invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='sales.invoiceline')),
            ],
            options={
                'ordering': ['credit_note', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['organization', 'status', 'credit_note_date'], name='sales_credi_organiz_4c68c2_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['organization', 'customer'], name='sales_credi_organiz_a22d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['organization', 'source_invoice'], name='sales_credi_organiz_f11576_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('credit_note_number', ''), _negated=True), fields=('organization', 'credit_note_number'), name='uniq_credit_note_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='creditnoteline',
            index=models.Index(fields=['credit_note', 'line_number'], name='sales_credi_credit__93dca3_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='credit_note_line_quantity_positive'),
        ),
    ]
