# Generated by Django 5.2.17 on 2026-09-15 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='amount_applied_to_invoice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
