# Generated by Django 5.2.17 on 2026-09-15 05:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
        ('inventory', '0007_alter_stockmovement_options_stockmovement_sequence'),
        ('items', '0002_enable_rls'),
        ('sales', '0015_creditnote_amount_applied_to_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoiceTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('due_days', models.PositiveIntegerField(default=0)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_templates', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tax_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoiceRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='sales.recurringinvoicetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceTemplateLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.recurringinvoicetemplate')),
            ],
            options={
                'ordering': ['template', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringinvoicetemplate',
            index=models.Index(fields=['organization', 'is_active', 'next_run_at'], name='sales_recur_organiz_9c619a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoicetemplate',
            index=models.Index(fields=['organization', 'customer'], name='sales_recur_organiz_0c689b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoicerun',
            index=models.Index(fields=['organization', 'template'], name='sales_recur_organiz_6c53d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoicerun',
            constraint=models.UniqueConstraint(fields=('template', 'occurrence_date'), name='uniq_recurring_run_per_occurrence'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoicetemplateline',
            index=models.Index(fields=['template', 'line_number'], name='sales_recur_templat_d62935_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoicetemplateline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recurring_line_quantity_positive'),
        ),
    ]
