# Generated by Django 5.2.17 on 2026-09-15 10:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_creditnote_cess_total_creditnote_cgst_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoicetemplateline',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
