# Generated by Django 5.2.17 on 2026-09-15 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_enable_rls'),
        ('accounts', '0003_seed_currencies'),
        ('purchases', '0003_expense_project'),
        ('sales', '0017_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('bank', 'Bank account'), ('credit_card', 'Credit card')], default='bank', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('branch_identifier', models.CharField(blank=True, max_length=32)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('provider_key', models.CharField(default='manual', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounting.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_start_date', models.DateField()),
                ('statement_end_date', models.DateField()),
                ('statement_closing_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('cleared_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='banking.bankaccount')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-statement_end_date'],
            },
        ),
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description_contains', models.CharField(blank=True, max_length=255)),
                ('counterparty_contains', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('any', 'Any'), ('inflow', 'Money in'), ('outflow', 'Money out')], default='any', max_length=8)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('action', models.CharField(choices=[('categorize', 'Categorize to an account'), ('exclude', 'Exclude from reconciliation')], default='categorize', max_length=16)),
                ('auto_confirm', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='banking.bankaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchases.vendor')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('duplicate_ordinal', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('suggested', 'Suggested'), ('matched', 'Matched'), ('excluded', 'Excluded')], default='unmatched', max_length=16)),
                ('excluded_reason', models.CharField(blank=True, max_length=255)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.bankaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.bankreconciliation')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=32)),
                ('transfer_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=16)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('accounting_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.currency')),
                ('from_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='banking.bankaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('to_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='banking.bankaccount')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('match_type', models.CharField(choices=[('exact', 'Exact (amount, date and reference)'), ('amount_date', 'Amount and date'), ('transfer', 'Transfer between own accounts'), ('rule', 'Reconciliation rule'), ('categorization', 'Categorized to an account'), ('manual', 'Chosen by a person')], max_length=16)),
                ('suggestion_source', models.CharField(choices=[('system', 'Deterministic matcher'), ('rule', 'Reconciliation rule'), ('user', 'Person'), ('ai', 'AI assistant')], default='system', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='sales.customerpayment')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='purchases.expense')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='accounting.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='banking.banktransaction')),
                ('vendor_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='purchases.vendorpayment')),
                ('bank_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='banking.banktransfer')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('qif', 'QIF'), ('feed', 'Bank feed'), ('manual', 'Manual entry')], max_length=16)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('statement_start_date', models.DateField(blank=True, null=True)),
                ('statement_end_date', models.DateField(blank=True, null=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped_duplicate', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='statement_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.statementimport'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['organization', 'is_active'], name='banking_ban_organiz_ad774b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_bank_account_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['organization', 'bank_account', 'statement_end_date'], name='banking_ban_organiz_5e1bd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('statement_end_date__gte', models.F('statement_start_date'))), name='bank_reconciliation_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('bank_account',), name='uniq_open_reconciliation_per_bank_account'),
        ),
        migrations.AddIndex(
            model_name='bankrule',
            index=models.Index(fields=['organization', 'is_active', 'priority'], name='banking_ban_organiz_f8f13d_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_bank_rule_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='bankrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_min__isnull', True), ('amount_max__isnull', True), ('amount_max__gte', models.F('amount_min')), _connector='OR'), name='bank_rule_amount_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='bankrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_min__isnull', True), ('amount_min__gte', 0), _connector='OR'), name='bank_rule_amount_min_non_negative'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['organization', 'transfer_date'], name='banking_ban_organiz_462d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['organization', 'from_bank_account'], name='banking_ban_organiz_9d5b86_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['organization', 'to_bank_account'], name='banking_ban_organiz_059261_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.UniqueConstraint(fields=('organization', 'transfer_number'), name='uniq_bank_transfer_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bank_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_bank_account', models.F('to_bank_account')), _negated=True), name='bank_transfer_distinct_accounts'),
        ),
        migrations.AddIndex(
            model_name='banktransactionmatch',
            index=models.Index(fields=['organization', 'transaction'], name='banking_ban_organiz_f9d02b_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionmatch',
            index=models.Index(fields=['organization', 'is_confirmed'], name='banking_ban_organiz_20991d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionmatch',
            index=models.Index(fields=['customer_payment'], name='banking_ban_custome_d07566_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionmatch',
            index=models.Index(fields=['vendor_payment'], name='banking_ban_vendor__69d142_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionmatch',
            index=models.Index(fields=['expense'], name='banking_ban_expense_68067b_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransactionmatch',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bank_match_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='banktransactionmatch',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='bank_match_confidence_in_range'),
        ),
        migrations.AddConstraint(
            model_name='banktransactionmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_payment__isnull', False), ('vendor_payment__isnull', True), ('expense__isnull', True), ('bank_transfer__isnull', True), ('journal_entry__isnull', True)), models.Q(('vendor_payment__isnull', False), ('customer_payment__isnull', True), ('expense__isnull', True), ('bank_transfer__isnull', True), ('journal_entry__isnull', True)), models.Q(('expense__isnull', False), ('customer_payment__isnull', True), ('vendor_payment__isnull', True), ('bank_transfer__isnull', True), ('journal_entry__isnull', True)), models.Q(('bank_transfer__isnull', False), ('customer_payment__isnull', True), ('vendor_payment__isnull', True), ('expense__isnull', True), ('journal_entry__isnull', True)), models.Q(('journal_entry__isnull', False), ('customer_payment__isnull', True), ('vendor_payment__isnull', True), ('expense__isnull', True), ('bank_transfer__isnull', True)), _connector='OR'), name='bank_match_exactly_one_counterpart'),
        ),
        migrations.AddIndex(
            model_name='statementimport',
            index=models.Index(fields=['organization', 'bank_account'], name='banking_sta_organiz_3be8e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='statementimport',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash', ''), _negated=True), fields=('bank_account', 'file_hash'), name='uniq_statement_file_hash_per_bank_account'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['organization', 'bank_account', 'transaction_date'], name='banking_ban_organiz_37ebce_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['organization', 'status'], name='banking_ban_organiz_716147_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'amount'], name='banking_ban_bank_ac_941a57_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('bank_account', 'fingerprint', 'duplicate_ordinal'), name='uniq_bank_transaction_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='bank_transaction_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'excluded'), ('excluded_reason', ''), _connector='OR'), name='bank_transaction_reason_only_when_excluded'),
        ),
    ]
