# Generated by Django 5.2.17 on 2026-09-16 09:41

import ai.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def require_pgvector(apps, schema_editor):
    """pgvector is an untrusted extension: only a superuser (or a managed
    database's admin role, e.g. RDS `rds_superuser`) can create it, and the
    application role deliberately is not one (backend/CLAUDE.md). Creation
    is an infrastructure step (infrastructure/postgres-init/02-pgvector.sql,
    the CI workflow, and the production runbook in ai/CLAUDE.md); this
    migration only verifies it and fails loudly and early if it is missing."""
    if schema_editor.connection.vendor != "postgresql":
        raise RuntimeError("The ai app requires PostgreSQL with the pgvector extension.")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_extension WHERE extname = 'vector'")
        if cursor.fetchone() is None:
            raise RuntimeError(
                "PostgreSQL extension 'vector' (pgvector) is not installed in this database. "
                "A superuser must run: CREATE EXTENSION IF NOT EXISTS vector; "
                "(and in template1 for the test database). See backend/ai/CLAUDE.md."
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        ('documents', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(require_pgvector, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('feature', models.CharField(max_length=40)),
                ('intent', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('no_data', 'No data found'), ('refused', 'Refused'), ('error', 'Error'), ('rate_limited', 'Rate limited')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('embedding_config_key', models.CharField(blank=True, max_length=200)),
                ('tool_names', models.JSONField(blank=True, default=list)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                ('retrieval_count', models.PositiveIntegerField(default=0)),
                ('llm_calls', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aiconversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('text_source', models.CharField(choices=[('ocr', 'OCR (completed)'), ('native_text', 'Native text file')], max_length=20)),
                ('document_type', models.CharField(max_length=20)),
                ('content_hash', models.CharField(max_length=64)),
                ('index_content_hash', models.CharField(max_length=64)),
                ('embedding', ai.fields.VectorField(blank=True, null=True)),
                ('embedding_provider', models.CharField(max_length=50)),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding_dimensions', models.PositiveIntegerField()),
                ('embedding_version', models.CharField(max_length=50)),
                ('embedding_config_key', models.CharField(max_length=200)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('text', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('not_indexable', 'Not indexable'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('text_source', models.CharField(blank=True, choices=[('ocr', 'OCR (completed)'), ('native_text', 'Native text file')], max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('embedding_config_key', models.CharField(blank=True, max_length=200)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_index', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['organization', 'user', 'last_message_at'], name='ai_aiconver_organiz_af749c_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['organization', 'conversation', 'created_at'], name='ai_aimessag_organiz_621fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['organization', 'created_at'], name='ai_aireques_organiz_7fd912_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['organization', 'user', 'created_at'], name='ai_aireques_organiz_fc8863_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['organization', 'embedding_config_key'], name='ai_document_organiz_f5c890_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['organization', 'document'], name='ai_document_organiz_791239_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ai_chunk_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_ai_chunk_per_document_index'),
        ),
        migrations.AddIndex(
            model_name='documentindex',
            index=models.Index(fields=['organization', 'status'], name='ai_document_organiz_bffa03_idx'),
        ),
        # Vectors are stored in a dimension-less `vector` column (ai/fields.py);
        # this keeps every stored vector's real dimension equal to the dimension
        # its embedding config declares, so two configs can never be confused.
        migrations.RunSQL(
            sql="ALTER TABLE ai_documentchunk ADD CONSTRAINT ai_chunk_embedding_dims_match "
                "CHECK (embedding IS NULL OR vector_dims(embedding) = embedding_dimensions);",
            reverse_sql="ALTER TABLE ai_documentchunk DROP CONSTRAINT IF EXISTS ai_chunk_embedding_dims_match;",
        ),
    ]
