# Generated by Django 5.2.17 on 2026-09-16 08:15

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], max_length=10)),
                ('mime_type', models.CharField(max_length=127)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('bank_statement', 'Bank Statement'), ('tax_document', 'Tax Document'), ('contract', 'Contract'), ('attachment', 'Attachment'), ('general', 'General')], default='general', max_length=20)),
                ('upload_status', models.CharField(choices=[('uploading', 'Uploading'), ('scanning', 'Scanning'), ('ready', 'Ready'), ('failed', 'Failed'), ('quarantined', 'Quarantined'), ('archived', 'Archived')], default='uploading', max_length=20)),
                ('ocr_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_requested', max_length=20)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('invoice', 'Invoice'), ('sales_order', 'Sales Order'), ('customer', 'Customer'), ('bill', 'Bill'), ('purchase_order', 'Purchase Order'), ('vendor', 'Vendor'), ('expense', 'Expense'), ('bank_transaction', 'Bank Transaction'), ('project', 'Project'), ('journal_entry', 'Journal Entry'), ('einvoice', 'e-Invoice'), ('ewaybill', 'e-Way Bill')], max_length=30)),
                ('entity_id', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_fields', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('notes', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTagAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.documenttag')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_version', models.CharField(blank=True, max_length=50)),
                ('raw_text', models.TextField(blank=True)),
                ('structured_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['organization', 'parent'], name='documents_d_organiz_8b4f2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('organization', 'parent', 'name'), name='uniq_folder_name_per_parent', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'created_at'], name='documents_d_organiz_f4cb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'document_type'], name='documents_d_organiz_408d81_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'upload_status'], name='documents_d_organiz_ceb020_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'ocr_status'], name='documents_d_organiz_2fc637_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'checksum_sha256'], name='documents_d_organiz_08de68_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['organization', 'entity_type', 'entity_id'], name='documents_d_organiz_47d237_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(fields=('document', 'entity_type', 'entity_id'), name='uniq_document_link'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['organization', 'status'], name='documents_d_organiz_b5ac76_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_tag_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='documenttagassignment',
            constraint=models.UniqueConstraint(fields=('document', 'tag'), name='uniq_tag_per_document'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['organization', 'provider'], name='documents_o_organiz_463089_idx'),
        ),
    ]
