# Generated by Django 5.2.17 on 2026-09-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_recovery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
