# Secrets Manager, not the repository/image/database (phase 12 section 6).
# Two kinds of entry here:
#  1. Generated by Terraform (Django SECRET_KEY, the app DB role's password)
#     — safe to generate randomly, nothing product-specific to decide.
#  2. Empty containers this file creates but never populates (AI/email/payment
#     provider keys, the automation webhook signing secret) — a real vendor
#     credential cannot be invented; populate these out-of-band (AWS console
#     or CLI) after apply, then reference them from the ECS task definitions
#     in ecs.tf. `ignore_changes` on secret_string keeps a later manual
#     rotation from being clobbered by the next `terraform apply`.

resource "random_password" "django_secret_key" {
  length  = 64
  special = true
}

resource "aws_secretsmanager_secret" "django_secret_key" {
  name = "${local.name}/django-secret-key"
}

resource "aws_secretsmanager_secret_version" "django_secret_key" {
  secret_id     = aws_secretsmanager_secret.django_secret_key.id
  secret_string = random_password.django_secret_key.result

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# The application's own non-superuser DB role (easybook_app locally — see
# infrastructure/postgres-init/01-app-role.sql). RDS's master credential
# (below, AWS-managed) must never be the runtime app user — global rule 4/
# backend/CLAUDE.md. Terraform cannot reach the private RDS instance to run
# `CREATE ROLE` itself; that is a documented one-time post-apply step (see
# infrastructure/terraform/README.md) using this generated password.
resource "random_password" "app_db_password" {
  length  = 32
  special = false # simplest to pass safely through every layer (env var, Secrets Manager, psql) without quoting surprises
}

resource "aws_secretsmanager_secret" "app_db_credentials" {
  name = "${local.name}/app-db-credentials"
}

resource "aws_secretsmanager_secret_version" "app_db_credentials" {
  secret_id = aws_secretsmanager_secret.app_db_credentials.id
  secret_string = jsonencode({
    username = "easybook_app"
    password = random_password.app_db_password.result
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- Empty containers: populate out-of-band, never in Terraform state ------

locals {
  empty_secret_containers = {
    ai-llm-provider-key        = "AI_* LLM provider API key (phase 12 section 67) — leave AI_ASK_BOOKS_ENABLED off until this is populated with a real, verified provider credential."
    ai-embedding-provider-key  = "AI_* embedding provider API key (phase 12 section 67-68), if the embedding provider is billed separately from the LLM provider."
    email-provider-credentials = "Transactional email provider (invoices, notifications, password reset)."
    automation-webhook-signing = "Default HMAC signing secret for automation outbound webhooks (phase 12 section 33) — each AutomationWebhookAction may still carry its own per-endpoint secret; see automation/CLAUDE.md."
  }
}

resource "aws_secretsmanager_secret" "empty" {
  for_each    = local.empty_secret_containers
  name        = "${local.name}/${each.key}"
  description = each.value
}
