# Generated by Django 5.2.17 on 2026-09-15 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('post', 'Post'), ('reverse', 'Reverse')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'object_type', 'object_id'], name='audit_audit_organiz_3ea24d_idx')],
            },
        ),
    ]
