/**
 * GENERATED FILE — do not edit by hand.
 * Source: backend/authz/roles.py
 * Regenerate: cd backend && .venv/Scripts/python.exe \
 *   ../frontend/scripts/generate-permissions.py
 *
 * This is a UI HINT ONLY (spec §62). It decides what to hide or disable so
 * the interface does not offer actions that will 403. It is NOT a security
 * boundary: authz.permissions.HasOrgPermission re-checks every request
 * server-side, and a 403 arriving anyway is handled as a normal outcome.
 *
 * Mirroring is safe here because the backend catalog is a closed set of code
 * constants that only changes on deploy — not per-organization rows. If the
 * backend ever gains custom roles, delete this file and read an authoritative
 * permission list off the session endpoint instead.
 */

export const ROLES = [
  "owner",
  "admin",
  "accountant",
  "staff",
  "viewer",
] as const;

export type Role = (typeof ROLES)[number];

export const ROLE_LABELS: Record<Role, string> = {
  "owner": "Owner",
  "admin": "Admin",
  "accountant": "Accountant",
  "staff": "Staff",
  "viewer": "Viewer",
};

export const PERMISSIONS = {
  MANAGE_ACCOUNTING: "accounting.manage",
  VIEW_ACCOUNTING: "accounting.view",
  USE_AI_ASSISTANT: "ai.ask",
  MANAGE_AI_INDEX: "ai.manage_index",
  VIEW_AI_USAGE: "ai.view_usage",
  CREATE_AUTOMATION: "automation.create",
  DISABLE_AUTOMATION: "automation.disable",
  EDIT_AUTOMATION: "automation.edit",
  ENABLE_AUTOMATION: "automation.enable",
  MANAGE_AUTOMATION_WEBHOOKS: "automation.manage_webhooks",
  RETRY_AUTOMATION: "automation.retry",
  RUN_AUTOMATION: "automation.run",
  VIEW_AUTOMATION: "automation.view",
  VIEW_AUTOMATION_HISTORY: "automation.view_history",
  IMPORT_BANK_STATEMENT: "banking.import_statement",
  MANAGE_BANK_ACCOUNTS: "banking.manage_bank_accounts",
  MANAGE_BANK_RULES: "banking.manage_rules",
  RECONCILE_BANK: "banking.reconcile",
  RECORD_BANK_TRANSFER: "banking.record_transfer",
  VIEW_BANK_ACCOUNTS: "banking.view_bank_accounts",
  VIEW_BANK_TRANSACTIONS: "banking.view_transactions",
  CANCEL_EINVOICE: "compliance.cancel_einvoice",
  CANCEL_EWAYBILL: "compliance.cancel_ewaybill",
  GENERATE_EINVOICE: "compliance.generate_einvoice",
  GENERATE_EWAYBILL: "compliance.generate_ewaybill",
  VIEW_RETURNS: "compliance.view_returns",
  DELETE_DOCUMENT: "documents.delete",
  DOWNLOAD_DOCUMENT: "documents.download",
  MANAGE_DOCUMENTS: "documents.manage",
  REVIEW_DOCUMENT_OCR: "documents.review_ocr",
  UPLOAD_DOCUMENT: "documents.upload",
  VIEW_DOCUMENTS: "documents.view",
  ADJUST_INVENTORY: "inventory.adjust",
  MANAGE_WAREHOUSES: "inventory.manage_warehouses",
  TRANSFER_INVENTORY: "inventory.transfer",
  VIEW_INVENTORY: "inventory.view",
  MANAGE_ITEMS: "items.manage",
  VIEW_ITEMS: "items.view",
  MANAGE_MEMBERS: "members.manage",
  MANAGE_ORGANIZATION: "organization.manage",
  APPROVE_TIME: "projects.approve_time",
  INVOICE_TIME: "projects.invoice_time",
  LOG_TIME: "projects.log_time",
  MANAGE_PROJECTS: "projects.manage_projects",
  VIEW_ALL_TIMESHEETS: "projects.view_all_timesheets",
  VIEW_PROJECTS: "projects.view_projects",
  CREATE_BILL: "purchases.create_bill",
  ISSUE_VENDOR_CREDIT: "purchases.issue_vendor_credit",
  MANAGE_EXPENSES: "purchases.manage_expenses",
  MANAGE_GOODS_RECEIPTS: "purchases.manage_goods_receipts",
  MANAGE_PURCHASE_ORDERS: "purchases.manage_purchase_orders",
  MANAGE_RECURRING_BILLS: "purchases.manage_recurring_bills",
  MANAGE_VENDORS: "purchases.manage_vendors",
  POST_BILL: "purchases.post_bill",
  RECORD_VENDOR_PAYMENT: "purchases.record_vendor_payment",
  VIEW_BILLS: "purchases.view_bills",
  VIEW_EXPENSES: "purchases.view_expenses",
  VIEW_GOODS_RECEIPTS: "purchases.view_goods_receipts",
  VIEW_PURCHASE_ORDERS: "purchases.view_purchase_orders",
  VIEW_RECURRING_BILLS: "purchases.view_recurring_bills",
  VIEW_VENDOR_CREDITS: "purchases.view_vendor_credits",
  VIEW_VENDOR_PAYMENTS: "purchases.view_vendor_payments",
  VIEW_VENDORS: "purchases.view_vendors",
  VOID_BILL: "purchases.void_bill",
  VIEW_REPORTS: "reports.view",
  CREATE_INVOICE: "sales.create_invoice",
  ISSUE_CREDIT_NOTE: "sales.issue_credit_note",
  MANAGE_CUSTOMERS: "sales.manage_customers",
  MANAGE_DELIVERIES: "sales.manage_deliveries",
  MANAGE_ORDERS: "sales.manage_orders",
  MANAGE_QUOTES: "sales.manage_quotes",
  MANAGE_RECURRING_INVOICES: "sales.manage_recurring_invoices",
  POST_INVOICE: "sales.post_invoice",
  RECORD_PAYMENT: "sales.record_payment",
  VIEW_CREDIT_NOTES: "sales.view_credit_notes",
  VIEW_CUSTOMERS: "sales.view_customers",
  VIEW_DELIVERIES: "sales.view_deliveries",
  VIEW_INVOICES: "sales.view_invoices",
  VIEW_ORDERS: "sales.view_orders",
  VIEW_PAYMENTS: "sales.view_payments",
  VIEW_QUOTES: "sales.view_quotes",
  VIEW_RECURRING_INVOICES: "sales.view_recurring_invoices",
  VOID_INVOICE: "sales.void_invoice",
  MANAGE_TAX_RATES: "tax.manage_rates",
  MANAGE_TAX_SETTINGS: "tax.manage_settings",
  VIEW_TAX_RATES: "tax.view_rates",
  VIEW_TAX_SETTINGS: "tax.view_settings",
  MANAGE_TRANSACTIONS: "transactions.manage",
  VIEW_TRANSACTIONS: "transactions.view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<Role, ReadonlySet<Permission>> = {
  "owner": new Set([
    "accounting.manage",
    "accounting.view",
    "ai.ask",
    "ai.manage_index",
    "ai.view_usage",
    "automation.create",
    "automation.disable",
    "automation.edit",
    "automation.enable",
    "automation.manage_webhooks",
    "automation.retry",
    "automation.run",
    "automation.view",
    "automation.view_history",
    "banking.import_statement",
    "banking.manage_bank_accounts",
    "banking.manage_rules",
    "banking.reconcile",
    "banking.record_transfer",
    "banking.view_bank_accounts",
    "banking.view_transactions",
    "compliance.cancel_einvoice",
    "compliance.cancel_ewaybill",
    "compliance.generate_einvoice",
    "compliance.generate_ewaybill",
    "compliance.view_returns",
    "documents.delete",
    "documents.download",
    "documents.manage",
    "documents.review_ocr",
    "documents.upload",
    "documents.view",
    "inventory.adjust",
    "inventory.manage_warehouses",
    "inventory.transfer",
    "inventory.view",
    "items.manage",
    "items.view",
    "members.manage",
    "organization.manage",
    "projects.approve_time",
    "projects.invoice_time",
    "projects.log_time",
    "projects.manage_projects",
    "projects.view_all_timesheets",
    "projects.view_projects",
    "purchases.create_bill",
    "purchases.issue_vendor_credit",
    "purchases.manage_expenses",
    "purchases.manage_goods_receipts",
    "purchases.manage_purchase_orders",
    "purchases.manage_recurring_bills",
    "purchases.manage_vendors",
    "purchases.post_bill",
    "purchases.record_vendor_payment",
    "purchases.view_bills",
    "purchases.view_expenses",
    "purchases.view_goods_receipts",
    "purchases.view_purchase_orders",
    "purchases.view_recurring_bills",
    "purchases.view_vendor_credits",
    "purchases.view_vendor_payments",
    "purchases.view_vendors",
    "purchases.void_bill",
    "reports.view",
    "sales.create_invoice",
    "sales.issue_credit_note",
    "sales.manage_customers",
    "sales.manage_deliveries",
    "sales.manage_orders",
    "sales.manage_quotes",
    "sales.manage_recurring_invoices",
    "sales.post_invoice",
    "sales.record_payment",
    "sales.view_credit_notes",
    "sales.view_customers",
    "sales.view_deliveries",
    "sales.view_invoices",
    "sales.view_orders",
    "sales.view_payments",
    "sales.view_quotes",
    "sales.view_recurring_invoices",
    "sales.void_invoice",
    "tax.manage_rates",
    "tax.manage_settings",
    "tax.view_rates",
    "tax.view_settings",
    "transactions.manage",
    "transactions.view",
  ]),
  "admin": new Set([
    "accounting.manage",
    "accounting.view",
    "ai.ask",
    "ai.manage_index",
    "ai.view_usage",
    "automation.create",
    "automation.disable",
    "automation.edit",
    "automation.enable",
    "automation.manage_webhooks",
    "automation.retry",
    "automation.run",
    "automation.view",
    "automation.view_history",
    "banking.import_statement",
    "banking.manage_bank_accounts",
    "banking.manage_rules",
    "banking.reconcile",
    "banking.record_transfer",
    "banking.view_bank_accounts",
    "banking.view_transactions",
    "compliance.cancel_einvoice",
    "compliance.cancel_ewaybill",
    "compliance.generate_einvoice",
    "compliance.generate_ewaybill",
    "compliance.view_returns",
    "documents.delete",
    "documents.download",
    "documents.manage",
    "documents.review_ocr",
    "documents.upload",
    "documents.view",
    "inventory.adjust",
    "inventory.manage_warehouses",
    "inventory.transfer",
    "inventory.view",
    "items.manage",
    "items.view",
    "members.manage",
    "projects.approve_time",
    "projects.invoice_time",
    "projects.log_time",
    "projects.manage_projects",
    "projects.view_all_timesheets",
    "projects.view_projects",
    "purchases.create_bill",
    "purchases.issue_vendor_credit",
    "purchases.manage_expenses",
    "purchases.manage_goods_receipts",
    "purchases.manage_purchase_orders",
    "purchases.manage_recurring_bills",
    "purchases.manage_vendors",
    "purchases.post_bill",
    "purchases.record_vendor_payment",
    "purchases.view_bills",
    "purchases.view_expenses",
    "purchases.view_goods_receipts",
    "purchases.view_purchase_orders",
    "purchases.view_recurring_bills",
    "purchases.view_vendor_credits",
    "purchases.view_vendor_payments",
    "purchases.view_vendors",
    "purchases.void_bill",
    "reports.view",
    "sales.create_invoice",
    "sales.issue_credit_note",
    "sales.manage_customers",
    "sales.manage_deliveries",
    "sales.manage_orders",
    "sales.manage_quotes",
    "sales.manage_recurring_invoices",
    "sales.post_invoice",
    "sales.record_payment",
    "sales.view_credit_notes",
    "sales.view_customers",
    "sales.view_deliveries",
    "sales.view_invoices",
    "sales.view_orders",
    "sales.view_payments",
    "sales.view_quotes",
    "sales.view_recurring_invoices",
    "sales.void_invoice",
    "tax.manage_rates",
    "tax.manage_settings",
    "tax.view_rates",
    "tax.view_settings",
    "transactions.manage",
    "transactions.view",
  ]),
  "accountant": new Set([
    "accounting.manage",
    "accounting.view",
    "ai.ask",
    "ai.manage_index",
    "automation.create",
    "automation.disable",
    "automation.edit",
    "automation.enable",
    "automation.retry",
    "automation.run",
    "automation.view",
    "automation.view_history",
    "banking.import_statement",
    "banking.manage_bank_accounts",
    "banking.manage_rules",
    "banking.reconcile",
    "banking.record_transfer",
    "banking.view_bank_accounts",
    "banking.view_transactions",
    "compliance.cancel_einvoice",
    "compliance.cancel_ewaybill",
    "compliance.generate_einvoice",
    "compliance.generate_ewaybill",
    "compliance.view_returns",
    "documents.delete",
    "documents.download",
    "documents.manage",
    "documents.review_ocr",
    "documents.upload",
    "documents.view",
    "inventory.view",
    "items.view",
    "projects.approve_time",
    "projects.invoice_time",
    "projects.log_time",
    "projects.manage_projects",
    "projects.view_all_timesheets",
    "projects.view_projects",
    "purchases.create_bill",
    "purchases.issue_vendor_credit",
    "purchases.manage_expenses",
    "purchases.manage_goods_receipts",
    "purchases.manage_purchase_orders",
    "purchases.manage_recurring_bills",
    "purchases.manage_vendors",
    "purchases.post_bill",
    "purchases.record_vendor_payment",
    "purchases.view_bills",
    "purchases.view_expenses",
    "purchases.view_goods_receipts",
    "purchases.view_purchase_orders",
    "purchases.view_recurring_bills",
    "purchases.view_vendor_credits",
    "purchases.view_vendor_payments",
    "purchases.view_vendors",
    "purchases.void_bill",
    "reports.view",
    "sales.create_invoice",
    "sales.issue_credit_note",
    "sales.manage_customers",
    "sales.manage_deliveries",
    "sales.manage_orders",
    "sales.manage_quotes",
    "sales.manage_recurring_invoices",
    "sales.post_invoice",
    "sales.record_payment",
    "sales.view_credit_notes",
    "sales.view_customers",
    "sales.view_deliveries",
    "sales.view_invoices",
    "sales.view_orders",
    "sales.view_payments",
    "sales.view_quotes",
    "sales.view_recurring_invoices",
    "sales.void_invoice",
    "tax.manage_rates",
    "tax.manage_settings",
    "tax.view_rates",
    "tax.view_settings",
    "transactions.manage",
    "transactions.view",
  ]),
  "staff": new Set([
    "accounting.view",
    "ai.ask",
    "automation.create",
    "automation.disable",
    "automation.edit",
    "automation.enable",
    "automation.retry",
    "automation.run",
    "automation.view",
    "automation.view_history",
    "banking.view_bank_accounts",
    "banking.view_transactions",
    "compliance.generate_ewaybill",
    "compliance.view_returns",
    "documents.download",
    "documents.upload",
    "documents.view",
    "inventory.adjust",
    "inventory.transfer",
    "inventory.view",
    "items.view",
    "projects.log_time",
    "projects.manage_projects",
    "projects.view_projects",
    "purchases.create_bill",
    "purchases.issue_vendor_credit",
    "purchases.manage_expenses",
    "purchases.manage_goods_receipts",
    "purchases.manage_purchase_orders",
    "purchases.manage_recurring_bills",
    "purchases.manage_vendors",
    "purchases.post_bill",
    "purchases.view_bills",
    "purchases.view_expenses",
    "purchases.view_goods_receipts",
    "purchases.view_purchase_orders",
    "purchases.view_recurring_bills",
    "purchases.view_vendor_credits",
    "purchases.view_vendor_payments",
    "purchases.view_vendors",
    "purchases.void_bill",
    "reports.view",
    "sales.create_invoice",
    "sales.issue_credit_note",
    "sales.manage_customers",
    "sales.manage_deliveries",
    "sales.manage_orders",
    "sales.manage_quotes",
    "sales.manage_recurring_invoices",
    "sales.post_invoice",
    "sales.record_payment",
    "sales.view_credit_notes",
    "sales.view_customers",
    "sales.view_deliveries",
    "sales.view_invoices",
    "sales.view_orders",
    "sales.view_payments",
    "sales.view_quotes",
    "sales.view_recurring_invoices",
    "sales.void_invoice",
    "tax.view_rates",
    "tax.view_settings",
    "transactions.manage",
    "transactions.view",
  ]),
  "viewer": new Set([
    "accounting.view",
    "ai.ask",
    "automation.view",
    "automation.view_history",
    "banking.view_bank_accounts",
    "banking.view_transactions",
    "compliance.view_returns",
    "documents.download",
    "documents.view",
    "inventory.view",
    "items.view",
    "projects.view_all_timesheets",
    "projects.view_projects",
    "purchases.view_bills",
    "purchases.view_expenses",
    "purchases.view_goods_receipts",
    "purchases.view_purchase_orders",
    "purchases.view_recurring_bills",
    "purchases.view_vendor_credits",
    "purchases.view_vendor_payments",
    "purchases.view_vendors",
    "reports.view",
    "sales.view_credit_notes",
    "sales.view_customers",
    "sales.view_deliveries",
    "sales.view_invoices",
    "sales.view_orders",
    "sales.view_payments",
    "sales.view_quotes",
    "sales.view_recurring_invoices",
    "tax.view_rates",
    "tax.view_settings",
    "transactions.view",
  ]),
};

/** Does this role grant this permission? Unknown roles grant nothing. */
export function roleHasPermission(role: Role | string | null | undefined, permission: Permission): boolean {
  if (!role) return false;
  const granted = ROLE_PERMISSIONS[role as Role];
  return granted ? granted.has(permission) : false;
}

/** True only when every listed permission is granted. */
export function roleHasAll(role: Role | string | null | undefined, permissions: readonly Permission[]): boolean {
  return permissions.every((permission) => roleHasPermission(role, permission));
}

/** True when at least one is granted — for a nav section covering several pages. */
export function roleHasAny(role: Role | string | null | undefined, permissions: readonly Permission[]): boolean {
  return permissions.some((permission) => roleHasPermission(role, permission));
}

export function permissionsForRole(role: Role | string | null | undefined): Permission[] {
  if (!role) return [];
  const granted = ROLE_PERMISSIONS[role as Role];
  return granted ? [...granted].sort() : [];
}
