# Generated by Django 5.2.17 on 2026-09-15 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('request_path', models.CharField(max_length=255)),
                ('request_body_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'key', 'request_path'), name='uniq_idempotency_key_per_org_path')],
            },
        ),
    ]
