# Generated by Django 5.2.17 on 2026-09-15 05:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enable_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='response_body',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
